// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("HttpFs.Core")>]
[<assembly: AssemblyProductAttribute("HttpFs.Core")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © 2018")>]
[<assembly: AssemblyDescriptionAttribute("Core types used by HttpFs runners")>]
[<assembly: AssemblyVersionAttribute("0.0.0")>]
[<assembly: AssemblyFileVersionAttribute("0.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "HttpFs.Core"
    let [<Literal>] AssemblyProduct = "HttpFs.Core"
    let [<Literal>] AssemblyCopyright = "Copyright © 2018"
    let [<Literal>] AssemblyDescription = "Core types used by HttpFs runners"
    let [<Literal>] AssemblyVersion = "0.0.0"
    let [<Literal>] AssemblyFileVersion = "0.0.0"
