// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("HttpFs")>]
[<assembly: AssemblyProductAttribute("HttpFs")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © 2018")>]
[<assembly: AssemblyDescriptionAttribute("A simple, functional HTTP client library for F#")>]
[<assembly: AssemblyVersionAttribute("5.0")>]
[<assembly: AssemblyFileVersionAttribute("5.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "HttpFs"
    let [<Literal>] AssemblyProduct = "HttpFs"
    let [<Literal>] AssemblyCopyright = "Copyright © 2018"
    let [<Literal>] AssemblyDescription = "A simple, functional HTTP client library for F#"
    let [<Literal>] AssemblyVersion = "5.0"
    let [<Literal>] AssemblyFileVersion = "5.0"
